### ISSUE TITLE
Get error "status": "RESOURCE_EXHAUSTED"

### ISSUE THREAD

**Issue by phucduong-ncc** [GoogleCloudPlatform/stable-diffusion-on-gcp#12]
Hello team
When i follow the guide in https://github.com/GoogleCloudPlatform/stable-diffusion-on-gcp/blob/main/Stable-Diffusion-Vertex/README.md

I run command:
gcloud ai custom-jobs create \
  --region=us-central1 \
  --display-name=trainiglora_dog \
  --config=vertex-config.yaml \
  --args="--model_name=runwayml/stable-diffusion-v1-5,--input_storage=/gcs/[gcbucket]/dog_images,--output_storage=/gcs/[gcbucket]/dog_lora_output,--prompt=a photo of alvan nee dog"

And always receive the error response
"error": {
    "code": 429,
    "message": "The following quota metrics exceed quota limits: aiplatform.googleapis.com/custom_model_training_nvidia_l4_gpus",
    "status": "RESOURCE_EXHAUSTED"
  }

Could you please advice me how to solve the problem
Thanks

**Comment by totorochina** [comment]
Hi `429, RESOURCE_EXHAUSTED` looks like you are running out of quota of using L4 GPUs. Go IAM -> Quota -> search `nvidia_l4_gpus` and see if you are out of quota. If yes, raise the quota.

Another way is to edit your `vertex-config.yaml`, update `acceleratorType` to another GPU type which you have quota.e.g. T4/V100, usually vRAM 16GB is enough for Lora training.

**Comment by phucduong-ncc** [comment]
hi @totorochina  yes the root cause because we running out of quota, thanks
