### ISSUE TITLE
Getting Error Cert Not Found

### ISSUE THREAD

**Issue by ranareehanmetex** [GoogleCloudPlatform/stable-diffusion-on-gcp#6]
metexlabz@cloudshekubectl get pods -n agones-systemle-Diffusion-UI-Agones/agones (ai-pictro-art)$ kubectl get pods -n agones-system
NAME                                 READY   STATUS             RESTARTS         AGE
agones-allocator-66dcf8957d-4n2zj    1/1     Running            0                38m
agones-allocator-66dcf8957d-8s4th    1/1     Running            0                38m
agones-allocator-66dcf8957d-jszhf    1/1     Running            0                38m
agones-controller-57cfd47-6qxw2      0/1     CrashLoopBackOff   12 (2m3s ago)    38m
agones-controller-57cfd47-rpx77      0/1     CrashLoopBackOff   12 (2m28s ago)   38m
agones-extensions-74dd86f699-6rtkf   0/1     CrashLoopBackOff   12 (2m3s ago)    38m
agones-extensions-74dd86f699-nsmwg   0/1     CrashLoopBackOff   12 (2m31s ago)   38m
agones-ping-5f96c6cc47-7sf2f         1/1     Running            0                38m
agones-ping-5f96c6cc47-8rtsq         1/1     Running            0                38m

agones-extensions-74dd86f699-nsmwg
back-off 5m0s restarting failed container=agones-extensions pod=agones-extensions-74dd86f699-nsmwg_agones-system(9f6e9f67-0676-46fb-9823-af8f4afb2186): CrashLoopBackOff
{
insertId: "x69d7hn1rlgaq5us"
jsonPayload: {
error: "Could not listen on :8081: open /home/agones/certs/server.crt: no such file or directory"
message: "could not start runner: *https.Server"
source: "main"
}

**Comment by totorochina** [comment]
Hi,

Fallback to agones 1.33 version may fix this problem.
```
helm install sd-agones-release --namespace agones-system -f ./agones/values.yaml agones/agones --version 1.33.0
```
